=  web

Repositori ini adalah sumber kode dari situs komunitas Go Indonesia,
https://golang-id.org.

Siapapun dapat berkontribusi dalam repositori ini.

Repositori ini menggunakan bahasa _markup_
https://asciidoctor.org/docs/what-is-asciidoc/[asciidoc] untuk
konten-kontennya.


==  Cara berkontribusi

Alur kerja untuk berkontribusi dalam repositori ini, baik dalam bentuk kode,
terjemahan, atau blog; sama dengan alur kerja pada proyek-proyek sumber
terbuka lainnya, yaitu dengan cara membuat salinan repositori lewat Github,
_commit_, dan buat _pull request_.

Untuk menghindari redundansi dan konflik, misalnya dua orang menerjemahkan
artikel yang sama, pastikan untuk melihat halaman
https://github.com/golang-id/web/issues[isu]
terlebih dahulu, apabila tidak ada yang mengklaim untuk menterjemahkan artikel
tersebut, buat isu baru dan nyatakan dalam isu tersebut artikel yang akan anda
terjemahkan.


==  Struktur direktori dan berkas

Repositori ini menggunakan konvensi direktori dan berkas yang sama dengan
https://github.com/shuLhan/ciigo[kerangkanya]:

*  `cmd/golangid`: direktori ini adalah program utama yang berisi konten
   statis.
   Program inilah yang nantinya melayani situs golang-id.org.

*  `content`: direktori ini berisi konten/halaman dari situs.
   Setiap halaman dibuat dengan menggunakan format asciidoc dan harus
   menggunakan ekstensi ".adoc".
   Berkas berekstensi selain ".adoc" akan diindahkan.

*  `content/assets`: direktori yang menyimpan berkas statis, seperti
   _stylesheet_.

*  `templates/html.tmpl`: berisi template yang membungkus hasil HTML dari
   berkas asciidoc.  Sebisa mungkin berkas ini tidak diubah dahulu, kecuali
   anda tahu yang anda lakukan.


==  Memulai pengembangan

Berikut langkah-langkah untuk memulai pengembangan di komputer anda,

.  Salin repositori ini ke dalam
   https://golang-id.org/doc/code.html#Workspaces[ruang-kerja] Go anda
+
----
$ mkdir -p $GOPATH/src/github.com/golang-id/web
$ cd $GOPATH/src/github.com/golang-id/web
$ git clone https://github.com/golang-id/web .
----

.  Jalankan perintah `go generate` untuk membangkitkan berkas HTML dari
   berkas-berkas asciidoc.
+
----
$ go generate
----

.  Jalankan program `golangid` di komputer anda dengan menset variabel
   lingkungan `DEBUG` dengan nilai `2`,
+
----
$ export DEBUG=2
$ ./golangid
----

.  Buka peramban dengan alamat http://127.0.0.1:5000.
   Situs lokal dari golang-id.org akan muncul di halaman tersebut.

.  Untuk membuat halaman baru, lihat contoh yang sudah ada dalam direktori
   "content".

.  Jika anda ingin menggabungkan pekerjaan anda, silahkan _commit_ dan _push_
   ke repositori anda sendiri dan buat _pull request_ ke repositori ini.
