=  Memulai dari Awal
:go-dl: https://golang.org/dl
:golang-doc-install-source: link:/doc/install/source/
:golang-doc-install-gccgo: link:/doc/install/gccgo/
:golang-id-list: https://groups.google.com/forum/#!forum/golang-id
:golang-cmd: https://golang.org/cmd/cgo
:golang-issue: https://github.com/golang-id/web/issues/new/choose
:xcode-app: https://developer.apple.com/Xcode/

Untuk cara pemasangan lainnya, Anda mungkin tertarik:

* link:/doc/install/source[Memasang Go dari sumber] - Bagaimana cara mengambil
  sumber kode, membangunnya pada mesin Anda, dan menjalankannya.


[#download]
==  *Unduh distribusi Go*

{go-dl}[Unduh Go].

{go-dl}[Distribusi biner resmi] tersedia untuk sistem operasi FreeBSD (rilis 10-STABLE
dan di atasnya), Linux, macOS (10.10 dan di atasnya), dan Windows dengan
prosesor arsitektur 32-bit (`386`) atau 64-bit (`amd64`) x86.

Jika distribusi biner tidak tersedia untuk kombinasi sistem operasi dan
arsitektur Anda, coba
{golang-doc-install-source}[pasang dari sumber] atau
{golang-doc-install-gccgo}[pasang gccgo sebagai ganti gc].


[#requirements]
==  *Kebutuhan sistem*

{go-dl}[Distribusi binari] dari Go tersedia untuk sistem operasi (SO) dan arsitektur
berikut.
Pastikan sistem Anda memenuhi kebutuhan ini sebelum melanjutkan.
Jika SO atau arsitektur tidak terdaftar, Anda mungkin bisa
{golang-doc-install-source}[memasang dari sumbernya langsung] atau
{golang-doc-install-gccgo}[menggunakan gccgo].

[.codetable,cols="2,2,4"]
|===
| Sistem operasi | Arsitektur | Catatan

| FreeBSD 10.3 atau terbaru
| amd64, 386
| Tidak mendukung Debian GNU/kFreeBSD

| Linux 2.6.23 atau terbaru dengan glibc
| amd64, 386, arm, arm64, s390x, ppc64le
| Tidak mendukung CentOS/RHEL 5.x.  Harus memasang dari sumber bila menggunakan libc yang lain.

| macOS 10.10 atau terbaru
| amd64
| Gunakan clang atau gcc† dari Xcode‡ untuk dukungan `cgo`

| Windows 7, Server 2008R2 atau terbaru
| amd64, 386
| Gunakan MinGW (`386`) atau MinGW-W64 (`amd64`) gcc†. Tidak perlu cygwin atau msys.
|===

† Membutuhkan _compiler_ C jika Anda berencana menggunakan {golang-cmd}[cgo].

‡ Anda hanya perlu memasang peralatan _command line_ untuk {xcode-app}[Xcode].
Jika Anda telah memiliki Xcode 4.3+, Anda bisa memasangnya dari panel
preferensi _Downloads_ pada tab _Components_.


[#install]
==  *Memasang Go*

Jika Anda ingin meningkatkan dari versi lama Anda harus
<<uninstall,menghapus versi yang terpasang>>.


[#tarball]
===  Pada Linux, macOS, dan FreeBSD dengan tarball

{go-dl}[Unduh arsip tersebut] dan ekstrak ke direktori `/usr/local`,
sehingga membuat `/usr/local/go`.
Sebagai contohnya:

  tar -C /usr/local -xzf go$VERSION.$OS-$ARCH.tar.gz

Pilih file arsip yang sesuai untuk instalasi Anda. 
Misalnya, jika Anda menginstal Go versi 1.2.1 untuk 64-bit x86 di Linux, 
arsip yang Anda inginkan disebut `go1.2.1.linux-amd64.tar.gz`.

(Biasanya, perintah tersebut harus dijalankan sebagai `root` atau dengan
`sudo`.)

Tambahkan `/usr/local/go/bin` ke variabel lingkungan `PATH`.
Anda bisa melakukan dengan menambahkan baris berikut pada `/etc/profile`
(untuk pemasangan secara global) atau `$HOME/.profile`:

  export PATH=$PATH:/usr/local/go/bin

*Catatan:* perubahan pada berkas `profile` tidak akan berlaku sampai Anda
`login` kembali ke komputer.
Untuk menerapkan perubahan secara langsung, cukup jalankan perintah tersebut
langsung dari _command prompt_ atau eksekusi berkas `profile` dengan cara
`source $HOME/.profile`.


[#macos]
===  Instalasi paket macOS

{go-dl}[Unduh berkas paket], buka, dan ikuti perintah untuk memasang
perkakas Go.
Paket tersebut akan memasang distribusi Go ke `/usr/local/go`.

Paket tersebut seharusnya menyimpan direktori `/usr/local/go/bin` ke variabel
lingkungan `PATH` Anda.
Anda perlu membuka sesi Terminal yang baru supaya perubahan langsung
diterapkan.


[#windows]
===  Windows

Go menyediakan dua opsi instalasi untuk pengguna Windows 
(selain {golang-doc-install-source}[menginstal dari sumber]): arsip zip yang 
mengharuskan Anda untuk mengatur beberapa variabel lingkungan dan pemasangan 
MSI yang mengkonfigurasi instalasi Anda secara otomatis.


====  Pemasangan MSI

Buka {go-dl}[berkas MSI] dan ikuti perintah untuk memasang perkakas Go.
Secara standar, paket tersebut memasang distribusi Go di `c:\\Go`.

Paket seharusnya menyimpan direktori `c:\\Go\\bin` dalam variabel lingkungan
`PATH` Anda secara otomatis.
Anda perlu membuka ulang _command prompt_ supaya perubahan langsung
diterapkan.

====  Arsip zip

{go-dl}[Unduh berkas zip] dan ekstrak ke direktori yang Anda pilih (kami
menyarankan `c:\\Go`).

Tambahkan sub-direktori `bin` dari Go (misalnya, `c:\\Go\\bin`) ke dalam
variabel lingkungan `PATH` Anda.


====  Pengaturan variabel lingkungan pada Windows

Dalam Windows, Anda bisa mengatur variabel lingkungan lewat tombol
"Environment Variables" pada tab "Advanced" dari panel kontrol "System".
Beberapa versi Windows menyediakan panel kontrol ini lewat opsi "Advanced
System Settings" di dalam panel kontrol "System".


[#testing]
==  *Menguji pemasangan*

Periksa bahwa Go terpasang dengan benar dengan cara membangun program sederhana, seperti berikut.

Buat file bernama `hello.go` yang berisi:

----
package main

import "fmt"

func main() {
        fmt.Printf("hello, world\n")
}
----

Kemudian bangun program dari kode tersebut dengan perkakas `go`:

----
$ go build hello.go
----

Perintah di atas akan membuat sebuah program bernama `hello` di dalam
direktori yang sama dengan kode.
Eksekusi program tersebut untuk melihat keluarannya,

----
$ ./hello
hello, world
----

Jika Anda melihat pesan "hello, world" maka instalasi Go Anda berjalan dengan
benar.

Sebelum bergegas menulis kode Go, mohon baca dokumen tentang
link:/doc/code.html[Cara Menulis Kode Go],
yang menjelaskan beberapa konsep utama tentang menggunakan perkakas Go.


[#extra_versions]
==  *Memasang versi Go tambahan*

Terkadang ada gunanya memiliki beberapa versi Go terpasang di mesin yang sama,
sebagai contohnya, untuk memastikan sebuah paket lulus dari pengujian beberapa
versi Go.
Setelah Anda memasang satu versi Go, Anda dapat memasang versi yang lain
(seperti versi 1.10.7) dengan cara:

----
$ go get golang.org/dl/go1.10.7
$ go1.10.7 download
----

Versi terunduh yang baru dapat digunakan seperti berikut:

----
$ go1.10.7 version
go version go1.10.7 linux/amd64
----

Semua versi Go yang dapat dipasang terdaftar di {go-dl}[halaman unduhan].
Anda bisa menemukan lokasi dari versi yang terpasang dengan melihat variabel
lingkungan `GOROOT`; sebagai contohnya, `go1.10.7 env GOROOT`.
Untuk menghapus versi yang terpasang, cukup hapus direktori `GOROOT` dan
biner `goX.Y.Z`.


[#uninstall]
==  *Menghapus pemasangan Go*

Untuk menghapus Go dari sistem Anda, hapus direktori `go`.
Pada Linux, macOS, dan FreeBSD, direktori tersebut ada di `/usr/local/go`,
pada Windows ada di `c:\\Go`.

Anda sebaiknya juga menghapus direktori Go `bin` dari variabel lingkungan
`PATH` Anda.
Pada Linux dan FreeBSD, Anda harus menyunting `/etc/profile` atau
`$HOME/.profile`.
Jika Anda memasang Go lewat <<macos,packet macOS>>, maka Anda harus menghapus
berkas `/etc/paths.d/go`.
Pengguna sistem Windows sebaiknya membaca bagian tentang
<<windows_env,pengaturan variabel lingkungan dalam Windows>>.


[#help]
==  *Bantuan*

Untuk bantuan, silakan tanyakan lewat {golang-id-list}[milis Go Indonesia].

Laporkan _bug_ di golang-id {golang-issue}[isu].
