=  Pustaka pihak-ketiga: goprotobuf dan lainnya
:author: Andrew Gerrand
:date: 20 April 2010


Pada tanggal 24 Maret, Rob Pike mengumumkan
https://code.google.com/p/goprotobuf/[goprotobuf^],
pustaka Go untuk format pertukaran data menggunakan
https://code.google.com/apis/protocolbuffers/docs/overview.html[Protocol Buffers^]
dari Google, disebut protobuf secara singkat.
Dengan pengumuman ini, Go bergabung dengan C++, Java, dan Python sebagai
bahasa yang menyediakan implementasi protobuf.
Hal ini menandai batu loncatan penting dalam membolehkan inter-operabilitas
antara sistem yang ada dan yang dibangun dengan Go.

Proyek goprotobuf terdiri dari dua bagian: sebuah '_plugin_ pengompilasi
protokol' yang membangkitkan sumber kode Go, yang bila dikompilasi, dapat
mengakses dan mengatur _protocol buffer_;
dan sebuah paket Go yang mengimplementasikan dukungan untuk _encoding_,
_decoding_, dan mengakses _protocol buffer_.

Untuk menggunakan goprotobuf, Anda perlu memasang Go dan
https://code.google.com/p/protobuf/[protobuf^].
Kemudian Anda dapat memasang paket 'proto' lewat
https://go.dev/cmd/goinstall/[goinstall^]:

----
goinstall goprotobuf.googlecode.com/hg/proto
----

Dan kemudian memasang plugin _compiler_ untuk protobuf:

----
cd $GOROOT/src/pkg/goprotobuf.googlecode.com/hg/compiler
make install
----

Untuk lebih jelas lihat berkas
https://code.google.com/p/goprotobuf/source/browse/README[README^]
dari proyek tersebut.

Ini adalah salah satu dari daftar pustaka pihak-ketiga dari
https://godashboard.appspot.com/package[proyek-proyek Go^]
yang terus berkembang.
Sejak diluncurkannya goprotobuf, Go _binding_ untuk X telah dipindahkan ke
proyek
https://code.google.com/p/x-go-binding/[x-go-binding^],
dan pekerjaan lain telah mulai mengimplementasikan
https://www.freetype.org/[Freetype^],
https://code.google.com/p/freetype-go/[freetype-go^].
Proyek pihak-ketiga lainnya yang terkenal termasuk kerangka kerja web ringan
https://github.com/hoisie/web.go[web.go^],
dan Go _binding_ untuk GTK
https://github.com/mattn/go-gtk[gtk-go^].

Kami mendorong pengembangan paket-paket berguna lainnya oleh komunitas sumber
terbuka.
Jika Anda sedang membuat sesuatu dengan Go, jangan simpan saja -- beri tahu
kami lewat _mailing list_
https://groups.google.com/group/golang-nuts[golang-nuts^].


==  Artikel terkait

*  link:/blog/a-new-go-api-for-protocol-buffers/[Go API baru untuk Protocol Buffers^],
*  link:/blog/go1.15-proposals/[Proposal untuk Go 1.15^],
*  link:/blog/survey2019/[Mengumumkan Survei Pengembang Go 2019^], 20 November

