=  Berkontribusi
:stylesheet: /assets/style.css
:golangid-isu: https://github.com/golang-id/web/issues

Halaman ini mendokumentasikan daftar pekerjaan yang dapat dilakukan untuk
situs golang-id.org.  Ada tiga komponen utama yang diharapkan oleh situs ini
sebagai komunitas Go Indonesia:

1.  Menerjemahkan artikel dari bahasa Inggris ke Bahasa Indonesia.
    Penerjemahan ini bertujuan untuk memudahkan pengguna baru dalam
    beradaptasi dan menggunakan Go.

2.  Mengumpulkan blog tentang Go yang ditulis oleh komunitas Go Indonesia.
    setiap blog nantinya dapat diakses lewat
    "https://golang-id.org/blog/YYYYMMDD_[judul]".

3.  Mengumpulkan repositori Go yang ditulis oleh komunitas Go Indonesia.
    Kumpulan repositori ini seperti
    https://github.com/avelino/awesome-go[awesome-go] namun khusus untuk
    komunitas Go Indonesia.


==  Daftar terjemahan

Daftar artikel yang rekomendasi untuk diterjemahkan, diurut berdasarkan
bagian:

*  Memasang Go

** https://golang.org/doc/install/source => /doc/install/source/index.adoc

** https://golang.org/doc/install/gccgo => /doc/install/gccgo/index.adoc

*  Wiki

** https://github.com/golang/go/wiki/Modules => /wiki/Modules/index.adoc

** https://github.com/golang/go/wiki/IDEsAndTextEditorPlugins => /wiki/IDEsAndTextEditorPlugins/index.adoc

*  Blog

**  https://blog.golang.org/errors-are-values => /blog/errors-are-values

**  https://blog.golang.org/profiling-go-programs =>
/blog/profiling-go-programs/index.adoc

*  Referensi

** https://golang.org/doc/cmd => /doc/cmd/index.adoc

** https://golang.org/doc/cmd/go => /doc/cmd/go/index.adoc

** https://golang.org/ref/mem => /ref/mem/index.adoc


==  Cara berkontribusi

Alur kerja untuk berkontribusi dalam repositori ini, baik dalam bentuk kode,
terjemahan, atau blog; sama dengan alur kerja pada proyek-proyek sumber
terbuka lainnya, yaitu dengan cara membuat salinan repositori lewat Github,
_commit_, dan buat _pull request_.

Untuk menghindari duplikat dan konflik, misalnya dua orang menerjemahkan
artikel yang sama, lihat halaman {golangid-isu}[isu] terlebih
dahulu, apabila tidak ada yang mengklaim untuk menerjemahkan artikel
tersebut, buat isu baru dan nyatakan dalam isu tersebut artikel yang akan anda
terjemahkan.

// TODO: jelaskan kata yang sebaiknya tidak disadur; menjaga hyperlink, supaya
// dapat diakses dengan cara mengganti url dari golang.org ke golang-id.org.


==  Struktur direktori dan berkas

Repositori ini menggunakan konvensi direktori dan berkas yang sama dengan
https://sr.ht/~shulhan/ciigo[kerangkanya]:

*  `cmd/www-golangid`: direktori ini adalah program utama yang berisi konten
   statis.
   Program inilah yang nantinya melayani situs golang-id.org.

*  `content`: direktori ini berisi konten/halaman dari situs.
   Setiap halaman dibuat dengan menggunakan format asciidoc dan harus
   menggunakan ekstensi ".adoc".
   Berkas memiliki ekstensi selain ".adoc" akan diindahkan.

*  `content/assets`: direktori yang menyimpan berkas statis, seperti
   _stylesheet_.

*  `templates/html.tmpl`: berisi template yang membungkus hasil HTML dari
   berkas asciidoc.  Sebaiknya berkas ini tidak diubah dahulu, kecuali
   anda tahu yang anda lakukan.


==  Memulai pengembangan

Berikut langkah-langkah untuk memulai pengembangan di komputer anda,

Salin repositori ini ke dalam
https://golang-id.org/doc/code.html#Workspaces[ruang-kerja]
Go anda

----
$ mkdir -p $GOPATH/src/github.com/golang-id/web
$ cd $GOPATH/src/github.com/golang-id/web
$ git clone https://github.com/golang-id/web .
----

Jalankan program `www-golangid` di komputer anda dengan men set variabel
lingkungan `DEBUG` dengan nilai `2`,

----
$ DEBUG=2 go run ./cmd/www-golangid
----

Jika ada eror seperti berikut,

----
Start: listen tcp :5000: bind: address already in use
----

itu berarti ada program lain yang telah menggunakan port 5000.
Anda bisa mengganti port ke yang lain, misalnya 5080,

----
$ DEBUG=2 go run ./cmd/www-golangid -port=5080
----

Jika berhasil maka Anda akan melihat keluaran seperti berikut,

----
....
ciigo: starting HTTP server at ":5000" for "./content"
....
----

Buka peramban pada alamat http://127.0.0.1:5000 (atau sesuai dengan port yang
Anda berikan).
Situs lokal dari golang-id.org akan muncul di halaman tersebut.

Untuk membuat halaman baru, lihat contoh yang sudah ada dalam direktori
"content".

Jika anda ingin menggabungkan pekerjaan anda, silakan _commit_ dan _push_
ke repositori anda sendiri dan buat _pull request_ ke repositori ini.

_Happy hacking!_
